### ISSUE TITLE
Updated install instructions?

### ISSUE THREAD

**Issue by animosity022** [itscontained/AutoMarkWatched#5]
I was trying to do a fresh install on another machine and it seems the install instructions are dated with a recent pull?

```
Generate secret_key python3 generate_secret_key.py
```

Doesn't seem to exist anymore and if I follow the remaining steps, I get a login screen for Django admin as it doesn't seem to create a user?

Is there a new set of steps to install from fresh?

**Comment by dirtycajunrice** [comment]
this project barely works. Im not a UI person. Django docs should explain how to generate a key though if you want to deal with all the caveats

**Comment by animosity022** [comment]
Ah, no problem. I can use the PlexAPI for this as well as it was a nice tool to make the front end a little bit smoother to operate. Thanks though for all your effort!
